version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 2.7

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)

  build:
    commands:
      - echo Building Docker image...
      - docker build -t slate-builder .
      - docker run --rm -v $PWD:/srv/slate -w /srv/slate slate-builder bundle exec middleman build

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  discard-paths: yes
