version: 0.2

phases:
  install:
    runtime-versions:
      ruby: 3.2

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - pip install awscli --upgrade
      - aws --version
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin

  build:
    commands:
      - echo Building Docker image...
      - docker build -t slate-builder .

  post_build:
    commands:
      - aws s3 cp --recursive . s3://youpay-documentation-api/
      - echo Build completed on `date`


artifacts:
  files:
    - '**/*'
  discard-paths: yes
